Month8/step2
Gyxer513/Stellar-Burgers pull request #4
Opened 2022-11-10 11:38 UTC by Gyxer513

2022-11-10 13:34 UTC, randomroot requested changes
**Доброго времени суток!**

Вы проделали **очень хорошую** работу по добавлению редакса и DnD в ваш проект, выстроили правильную **файловую структуру**, разделив экшены и редьюсеры по сущностям, выдели отдельные функции под каждый диспатч, так держать👍 

Тем не менее, для успешной сдачи работы, вам необходимо внимательно изучить комментарии к вашему коду, указанные в рамках ревью, в том числе:

**Нужно исправить:**

- В стоимости заказа должны учитываться 2 булки;
- Функционал отправки заказа целесообразно перенести в компонент `BurgerConstructor`, т.к. именно он осуществляет работу с заказом. Файл `App.jsx` является одной из точек входа в приложение и его лучше держать чистым;
- После оформления заказа следует сбросить стор, чтобы обнулить конструктор ингредиентов и при следующем заказе не отображать в модальном окне старый номер;
- Не целесообразно генерировать массив идентификаторов для заказа на каждом изменении списка ингредиентов или булки, достаточно сделать это один раз в момент отправки заказа;
- Передача в `payload` функции `console.log` является некорректным, по причине того, что она не возвращает значение. Плюс, параметр `payload` не является обязательным, поэтому вызов логгирование можно произвести просто до диспатча;

**Можно улучшить:**

- Часть логики связанной с формирование нового массива имеет смысл вынести непосредственно в редьюсер, чтобы уменьшить количество бизнес-логики в компонентах и отправлять из них только параметры, необходимые для обновления;
- Обратите внимание на предложенный в комментарии алгоритм для счетчика в ингредиенте, есть возможность оптимизации процесса подсчёта;

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**.

---

**Успешного вам рефакторинга и хорошего настроения!** 🐈

2022-11-10 13:34 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +      chosenBun?.price +
🔴 **Нужно исправить:**

 В стоимости заказа должны учитываться 2 булки

2022-11-10 13:34 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +        dispatch(addIngredient([...chosenIngredients, targetIngredient]));
🟡 **Можно улучшить:**

Имеет смысл перенести логику добавления в массив непосредственно в редьюсер, а из компонента отправлять только новый элемент в диспатч, чтобы разделить бизнес-логику работы стора и код, связанный с рендерингом в рамках компонента

2022-11-10 13:34 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +    <DndProvider backend={HTML5Backend}>
🔴 **Нужно исправить:**

`DndProvider` уже присутствует в родительском компоненте, поэтому его не следует дублировать тут

2022-11-10 13:34 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +            {!totalPrice ? 0 : totalPrice}
🟡 **Можно улучшить:**

Можно упростить до `totalPrice || 0`

2022-11-10 13:34 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +              chosenIngredients.length > 0 || chosenBun != null ? false : true
🟡 **Можно улучшить:**

Выражение можно заменить на `chosenIngredients.length === 0 && chosenBun === null` вместо тернарного оператора

2022-11-10 13:34 UTC, randomroot commented on src/services/actions/order.js
> +          payload: console.log(error),
🔴 **Нужно исправить:**

`console.log` не возвращает результат, это `void` функция

2022-11-10 13:34 UTC, randomroot commented on src/services/actions/ingredients.js
> +  const newBan = Object.assign(  {randomId: randomId()}, addedBun);
🟡 **Можно улучшить:**

Допущена орфографическая ошибка

2022-11-10 13:34 UTC, randomroot commented on src/components/app/App.jsx
>    const orderList = React.useMemo(
🔴 **Нужно исправить:**

Не целесообразно генерировать массив идентификаторов для заказа на каждом изменении списка ингредиентов или булки, достаточно сделать это один раз в момент отправки заказа :)

2022-11-10 13:34 UTC, randomroot commented on src/services/actions/ingredients.js
> +          payload: console.log(error),
🔴 **Нужно исправить:**

`console.log` не возвращает результат, это `void` функция

2022-11-10 13:34 UTC, randomroot commented on src/services/actions/order.js
> +        if (data) {
🟡 **Можно улучшить:**

При отсутствии `data` имеет смысл вызывать диспатч ошибки, чтобы сигнализировать о том, что запрос вернул некорректный результат

2022-11-10 13:34 UTC, randomroot commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +        <Tab value="one" active={current === "one"} onClick={handleTabClick}>
🟡 **Можно улучшить:**

Вместо значений `one`...`three` имеет смыл использовать более подходящие по смыслу, например тип ингредиентов: `bun`, `sauce`, `main`

2022-11-10 13:34 UTC, randomroot commented on src/components/BurgerIngredients/BurgerIngredients.jsx
>    const [current, setCurrent] = React.useState("one");
🟡 **Можно улучшить:**

Варианты значения стейта имеет смысл вынести в отдельные константы или объединить под одной константой, чтобы их было удобно переиспользовать в рамках файла и при необходимости изменить содержимое только в одном месте, вместо множества, например:
```typescript
const Tabs = {
  BUN: 'bun',
  SAUCE: 'sauce'
  ...
}

... = useState(Tabs.BUN)
```

2022-11-10 13:34 UTC, randomroot commented on src/components/BurgerIngridient/BurgerIngredient.jsx
> +      chosenIngredients?.forEach((ingredient) => {
🟡 **Можно улучшить:**

Подсчёт кол-ва элементов, добавленных в конструктор осуществляется правильно, однако не совсем оптимально, по причине того, что для каждого ингредиента осуществляется полный проход по всему массиву ингредиентов в поиске совпадающих. Если считать, что длина массива = N, то сложность данного алгоритма в целом для всех элементов = O(N*N), что при большом количестве элементов может ухудшать производительность вашего проекта.

Для оптимизации данного процесса имеет смысл рассмотреть альтернативный путь подсчёта, например проводить его в сторе, храня значения счётчиков там в отдельном объекте и изменяя его показатели при каждом добавлении/удалении элемента. Таким образом, вычислительная сложность уменьшается до O(1), т.к. сложность процесса вычисления не будет зависеть от размера массива.

О вычислительной сложности можно прочитать например здесь: https://tproger.ru/articles/computational-complexity-explained/

2022-11-10 13:34 UTC, randomroot commented on src/components/BurgerIngridient/BurgerIngredient.jsx
> +      {count() > 0 && (
🟡 **Можно улучшить:**

Не следует вызывать функцию `count` дважды, лучше использовать `useMemo` и вычислять значение в константу, которую здесь переиспользовать

2022-11-10 13:34 UTC, randomroot commented on src/components/BurgerIngridient/BurgerIngredient.jsx
> +      <img className="ingridient__image" src={image} alt={name} id={_id} />
🟡 **Можно улучшить:**

Допущена орфографическая ошибка

2022-11-10 13:34 UTC, randomroot commented on src/components/BurgerIngridient/BurgerIngredient.jsx
> +        if (ingredient.name === name) {
🟡 **Можно улучшить:**

Т.к. у каждого ингредиента есть свой уникальный ID, то лучше ориентироваться на него, чем на имя. Так операция сравнения будет по времени одинакова для любого элемента, неважно из 1 или 100 символов у него название :)

2022-11-10 13:34 UTC, randomroot commented on src/components/BurgerConstructor/ConstructorItem.jsx
> +    arrayClone.splice(chosenIngredients.indexOf(item), 1);
🟡 **Можно улучшить:**

Удаление элемента можно провести проще, если воспользоваться функцией `filter` по его идентификатору :)

2022-11-11 05:48 UTC, Gyxer513 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +    <DndProvider backend={HTML5Backend}>
Исправлено.

2022-11-11 05:49 UTC, Gyxer513 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +            {!totalPrice ? 0 : totalPrice}
Исправлено.

2022-11-11 05:52 UTC, Gyxer513 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +              chosenIngredients.length > 0 || chosenBun != null ? false : true
Заменено на !totalPrice || 0, так запись еще короче.

2022-11-11 05:53 UTC, Gyxer513 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +      chosenBun?.price +
Исправлено.

2022-11-11 05:57 UTC, Gyxer513 commented on src/components/BurgerIngridient/BurgerIngredient.jsx
> +      <img className="ingridient__image" src={image} alt={name} id={_id} />
Исправлено.

2022-11-11 07:03 UTC, Gyxer513 commented
Логика отправки запроса перенесена в OrderDetails, запрос оправляется при монтировании компонента. Компонент BurgerConstructor  уже очень перегружен кодом.

2022-11-11 07:20 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, так держать👍

Хорошая работа, **желаю вам отличного дня и успехов в дальнейшем обучении**! 🐈

2022-11-11 07:39 UTC, merged