Month9/step1
Gyxer513/Stellar-Burgers pull request #6
Opened 2022-12-17 01:27 UTC by Gyxer513

2022-12-17 03:58 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Вы используйте React Router;
- Теперь в приложении есть авторизация;

### **Но есть несколько замечаний, которые нужно исправить:**

- Нужно исправить ошибку, без этого приложение не запускается.
  https://yadi.sk/d/NgUXMYq4NUN68g

- Заказ не должен отправляться если нет булок и ингредиентов.

- Вы должны отлавливать ошибки во всех асинхронных экшенах. https://redux-toolkit.js.org/api/createAsyncThunk#handling-thunk-results

- Не реализована функциональность, а также страница для роута `/reset-password`.

- Вы никак не сохраняете токены, и поэтому при перезагрузке страницы пользователь снова должен логинится в систему, лучше всего сохранять токены в куках.

- При запросах, использующих accessToken, проверяется ответ сервера. Если время жизни токена истекло, то выполняется запрос обновления токена и повторяется запрос, который не был выполнен успешно.

- По чек-листу. Если пользователь отредактировал свои данные в форме на странице `/profile`, то появляются кнопки «Отмена» и «Сохранить».

  Если изменить только имя, или только email, то кнопка не появляется.

- По чек-листу. При клике на «История заказов» происходит переход на экран /profile/orders, ссылка «История заказов» становится активной, экран /profile/orders пока отображается пустым.

### **Сделает код лучше:**

- Стоит обращать внимание на замечание в терминале, и по возможности их устранять.

- На странице `/ingredients/:id`, при закрытии модального окна, пользователя лучше перенаправлять на главную страницу проекта.

2022-12-17 03:58 UTC, ArslanDev666 commented on src/components/BurgerIngridient/BurgerIngredient.jsx
>    const count = () => {
**Можно лучше:**

Тут стоит использовать useMemo)

2022-12-17 03:58 UTC, ArslanDev666 commented on src/components/Protected-route/ProtectedRoute.jsx
> +        isAuthorizationSucsess ? children : <Redirect to="/login" />
**Надо исправить:** 

Почему бы не сделать просто ранний возврат из функции. 

```js

if(!isAuthorizationSucsess) return (<Redirect to="/login" />);

return (
    <Route
      {...props} 
      ...
```

2022-12-17 03:58 UTC, ArslanDev666 commented on src/pages/fogot-password/ForgotPassword.jsx
> +    console.log(emailValue);
**Надо исправить:**

В приложении не должно быть логов или дебаггеров.

2022-12-17 03:58 UTC, ArslanDev666 commented on src/pages/fogot-password/ForgotPassword.jsx
> +    ).then((res) => console.log(res));
**Надо исправить:**

В приложении не должно быть логов или дебаггеров.

2022-12-17 03:58 UTC, ArslanDev666 commented on src/services/reducers/authorization.js
> +/* ***** Регистрация нового пользователя ***** */
**Вы молодец:**

🔥 Круто что вы оставляете комментарии к коду!)

2022-12-17 03:58 UTC, ArslanDev666 commented on src/services/reducers/ingredients.js
> +    selectIngredient: {},
**Надо исправить:**

Если значения нет, то нужно использовать null, а не пустой объект.

2022-12-17 03:58 UTC, ArslanDev666 commented on src/services/reducers/ingredients.js
> +        state.selectIngredient = {};
Вот тут тоже не забудьте заменить {} на `null`.

2022-12-17 03:58 UTC, ArslanDev666 commented on src/components/app/App.jsx
> +    dispatch(getData());
**Надо исправить:**

Исправьте во всём проекте.

Вы должны отлавливать ошибки во всех асинхронных экшенах.

https://redux-toolkit.js.org/api/createAsyncThunk#handling-thunk-results

2022-12-19 20:26 UTC, Gyxer513 commented on src/pages/fogot-password/ForgotPassword.jsx
> +    ).then((res) => console.log(res));
Исправлено.

2022-12-19 20:27 UTC, Gyxer513 commented on src/services/reducers/authorization.js
> +/* ***** Регистрация нового пользователя ***** */
Спасибо)

2022-12-19 20:28 UTC, Gyxer513 commented on src/services/reducers/ingredients.js
> +    selectIngredient: {},
Исправлено.

2022-12-19 20:29 UTC, Gyxer513 commented on src/components/app/App.jsx
> +    dispatch(getData());
Исправлено, функционал добавлен в редьюсеры.

2022-12-19 20:30 UTC, Gyxer513 commented on src/pages/fogot-password/ForgotPassword.jsx
> +    console.log(emailValue);
Исправлено.

2022-12-19 20:35 UTC, Gyxer513 commented on src/components/BurgerIngridient/BurgerIngredient.jsx
>    const count = () => {
Исправлено.

2022-12-19 22:21 UTC, Gyxer513 commented on src/components/BurgerIngridient/BurgerIngredient.jsx
>    const count = () => {
Вернул начальный вариант, так как ошибку победить не удалось... 
![image](https://user-images.githubusercontent.com/102280477/208538018-37128fc7-aa7f-40ae-88be-f4071f137071.png)

2022-12-19 22:21 UTC, Gyxer513 commented on src/components/BurgerIngridient/BurgerIngredient.jsx
>    const count = () => {
Вот реализация. 

![image](https://user-images.githubusercontent.com/102280477/208538101-2162ebad-d2b8-478a-ae00-5aba5815c7f3.png)

2022-12-19 22:25 UTC, Gyxer513 commented on src/components/Protected-route/ProtectedRoute.jsx
> +        isAuthorizationSucsess ? children : <Redirect to="/login" />
Исправлено.

2022-12-20 03:34 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Практически все замечания с прошлого ревью были исправлены;

### **Но всё ещё есть несколько замечаний, которые нужно исправить:**

- Заказ не должен отправляться если нет булок и ингредиентов. Т.е. должно быть и то, и то, а не что-то одно.

- При выходе вы не очищаете куки, поэтому после выхода пользователь может без логина сделать заказ, зайти на страницу профиля, и т.п.

- По чек-листу. Если пользователь отредактировал свои данные в форме на странице `/profile`, то появляются кнопки «Отмена» и «Сохранить».

  Выдаёт ошибку, что пользователь не залогинен.

  https://disk.yandex.ru/i/y3TeLb5ntYWiPg - на видео также показан как воспроизвести предыдущий пункт.

- По чек-листу. При клике на «История заказов» происходит переход на экран /profile/orders, ссылка «История заказов» становится активной, экран /profile/orders пока отображается пустым.

  У вас есть переход, но ссылка не выделяется. https://yadi.sk/d/cphxcoKWs6sFHA;

2022-12-20 03:34 UTC, ArslanDev666 commented on src/components/BurgerIngridient/BurgerIngredient.jsx
>    const count = () => {
ну я имел ввиду не handleClick, а count ), гитхаб просто не может отображать 1 строчку, поэтому отображает 4 предыдущих.

![image](https://user-images.githubusercontent.com/70164458/208573198-7e88d384-e478-4426-961f-1bcbbb267453.png)

2022-12-20 08:09 UTC, Gyxer513 commented
Здравствуйте! Спасибо за ревью.

Все замечания исправлены.

2022-12-20 20:28 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Практически все замечания с прошлого ревью были исправлены 🔥;

### **Но есть 1 небольшое замечание, которое нужно исправить:**

- Отметил в коде.

  Когда пользователь залогинен. Если он попробует сразу загрузить страницу профиля, то он попадает на страницу логина. Это происходит из-за компонента protectRoute, вам нужно дождаться пока данные придут с сервера, и только потом делать проверки.

2022-12-20 20:28 UTC, ArslanDev666 commented on src/components/Protected-route/ProtectedRoute.jsx
> +export const ProtectedRoute = ({ children, ...props }) => {
**Надо исправить:**

Авторизация по прежнему работает немного криво, это связано с этим роутом. 
Вам нужно дождаться пока выполниться запрос на сервер, и только потом проверять `isAuthorizationSucsess` или нет.

2022-12-21 04:55 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении.**

### **Также рекомендую исправить отмеченные замечания (и ещё 1 в коде):**

- https://yadi.sk/d/Yq_SqDc6OIMfxw - должна быть активна только та ссылка, на которой сейчас находится пользователь.

2022-12-21 04:55 UTC, ArslanDev666 commented on src/components/Protected-route/ProtectedRoute.jsx
> +  if (!isAuthorizationSucsess && !userData) return <Redirect to="/login" />;
**Надо исправить:**

Вам нужно вставить вот это перед проверкой на авторизацию, и тогда всё будет отлично работать)

```js
if(!userData) return <Loader />
```

2022-12-21 09:44 UTC, merged