Month10/step1
Gyxer513/Stellar-Burgers pull request #8
Opened 2023-01-23 12:26 UTC by Gyxer513

2023-01-23 13:47 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Проект теперь типизирован;

### **Но есть несколько замечаний, которые нужно исправить:**

- Вам нужно типизировать все action в extraReducers и reducers, используйте для этого тип `PayloadAction`.

- Вы немного перепутали тип кортежа и массивов, советую ещё раз ознакомится с этими темами.
  <https://www.typescriptlang.org/docs/handbook/2/objects.html#tuple-types> - кортежи
  <https://www.typescriptlang.org/docs/handbook/2/objects.html#the-array-type> - массивы

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

### **После исправления всех замечаний, работа будет принята)**

2023-01-23 13:47 UTC, ArslanMustafin commented on src/components/IngredientDetails/IngredientDetails.tsx
> +  const { id } = useParams<any>();
**Надо исправить:** 

Тут вы должны указать type или interface именно для тех данных которые хотите достать))

```js
type UrlParamsType = { id: string };

const { id } = useParams<UrlParamsType>();
```

2023-01-23 13:47 UTC, ArslanMustafin commented on src/pages/fogot-password/ForgotPassword.tsx
> +  const onChange = (e: any) => {
**Надо исправить:**

Здесь и в других похожих местах.

У React есть специальный тип для обработчиков событий элементов формы - это ChangeEvent<T> и FormEvent<T>, рекомендую использовать именно ChangeEvent для onChange событий инпутов, а FormEvent для submit события формы.

```js
  const onChange = (e: ChangeEvent<HTMLInputElement>) => {...}
```

2023-01-23 13:47 UTC, ArslanDev666 commented on src/components/app/App.tsx
> +  const location = useLocation<ILocationState & { background: Location }>();
**Можно лучше:**

Немного не понимаю зачем вы дополнительно объединяете `background`, если он уже есть у вас в типе ILocationState

2023-01-23 13:47 UTC, ArslanDev666 commented on src/components/Protected-route/ProtectedRoute.tsx
> +  const location = useLocation<ILocationState & { background: Location }>();
**Можно лучше:**

Немного не понимаю зачем вы дополнительно объединяете `background`, если он уже есть у вас в типе ILocationState

2023-01-23 13:47 UTC, ArslanDev666 commented on src/services/store.ts
> +export type AppDispatch = typeof store.dispatch
**Можно лучше:**

Почему бы вам сразу не обьявить dispatch с правильным типом?

```js
type AppDispatch = typeof store.dispatch
type DispatchFunc = () => AppDispatch
export const useAppDispatch: DispatchFunc = useDispatch
```

А то вы каждый раз указываете тип, когда используете dispatch))

2023-01-23 13:47 UTC, ArslanDev666 commented on src/services/reducers/ingredients.ts
>        },
**Надо исправить:**

Тут у вас передаётся 1 ингредиент и должен быть указан тип ингредиента.

```js
action: PayloadAction<IIngredient>
```

2023-01-23 13:47 UTC, ArslanDev666 commented on src/services/types/store.ts
> +  ingredients: [Iingredient] | [];
**Надо исправить:**

Здесь и далее.

Вы неправильно указываете тип, сейчас вы указали что ingredients - это кортеж, из 1 элемента типа `Iingredient`. А вам тут нужно указать просто массив.

```js
  ingredients: Iingredient[];
```

2023-01-23 13:47 UTC, ArslanDev666 commented on src/services/reducers/authorization.ts
> +      .addCase(registerNewUser.fulfilled, (state, action) => {
**Надо исправить:**

Здесь и далее.

Вам нужно типизировать все action в extraReducers, используйте для этого тип `PayloadAction`

2023-01-23 13:47 UTC, ArslanDev666 commented on src/services/reducers/ingredients.ts
> +      .addCase(getData.fulfilled, (state, action) => {
**Надо исправить:**

Здесь и далее.

Вам нужно типизировать все action в extraReducers, используйте для этого тип `PayloadAction`

2023-01-23 13:47 UTC, ArslanDev666 commented on src/services/reducers/order.ts
> +    .addCase(sendOrder.fulfilled, (state, action) => {
**Надо исправить:**

Здесь и далее.

Вам нужно типизировать все action в extraReducers, используйте для этого тип `PayloadAction`

2023-01-23 13:47 UTC, ArslanDev666 commented on src/services/types/ingredients.ts
> +  orders: [IOrderFullInfo]
**Надо исправить:**

Тут вы используете кортеж, а вам надо использовать массив.

```js
  orders: IOrderFullInfo[]
```

2023-01-23 13:47 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +// @ts-ignore
**Надо исправить:**

После того как замените кортежи на массив, то это нужно убрать)) тс по идее ругаться не должен.

2023-01-23 13:47 UTC, ArslanDev666 commented on src/components/BurgerConstructor/ConstructorItem.tsx
> +  const handleDeleteIngredient = (item: Iingredient | unknown) => () => {
**Можно лучше:**

не совсем понимаю, зачем вам тут тип unknown))

2023-01-23 13:47 UTC, ArslanDev666 commented on src/components/BurgerConstructor/ConstructorItem.tsx
> +    // @ts-ignore
**Надо исправить:**

После того как замените кортежи на массив, то это нужно убрать)) тс по идее ругаться не должен.

2023-01-23 13:47 UTC, ArslanDev666 commented on src/services/types/types.ts
> +  ingredients: [string];
**Надо исправить:**

Тут должен быть массив ингредментов, а не кортеж из 1 строки.
```js
  ingredients: Iingredient[];
```

2023-01-23 15:14 UTC, Gyxer513 commented on src/components/IngredientDetails/IngredientDetails.tsx
> +  const { id } = useParams<any>();
Исправлено.

2023-01-23 15:20 UTC, Gyxer513 commented on src/pages/fogot-password/ForgotPassword.tsx
> +  const onChange = (e: any) => {
Исправлено.

2023-01-23 15:21 UTC, Gyxer513 commented on src/components/app/App.tsx
> +  const location = useLocation<ILocationState & { background: Location }>();
Проект запускался с ошибками, так как была случайно обновлена версия React Router. Версию откатил, лишнее убрал.

2023-01-23 15:23 UTC, Gyxer513 commented on src/components/Protected-route/ProtectedRoute.tsx
> +  const location = useLocation<ILocationState & { background: Location }>();
Исправлено.

2023-01-23 15:30 UTC, Gyxer513 commented on src/services/store.ts
> +export type AppDispatch = typeof store.dispatch
Не хотелось копировать с документации под копирку. 
![image](https://user-images.githubusercontent.com/102280477/214079851-b55d4124-574a-4d40-8fcd-d6cdf720e550.png)

2023-01-23 15:45 UTC, Gyxer513 commented on src/services/types/store.ts
> +  ingredients: [Iingredient] | [];
Исправлено.

2023-01-23 15:51 UTC, Gyxer513 commented on src/components/BurgerConstructor/ConstructorItem.tsx
> +  const handleDeleteIngredient = (item: Iingredient | unknown) => () => {
Исправлено.

2023-01-23 15:54 UTC, Gyxer513 commented on src/services/types/types.ts
> +  ingredients: [string];
Исправлено.

2023-01-23 16:03 UTC, Gyxer513 commented on src/components/BurgerConstructor/ConstructorItem.tsx
> +    // @ts-ignore
Не помогает, TS ругается либо на item (он ждет тип never), либо на типизацию data на 86 строке.

2023-01-23 16:05 UTC, Gyxer513 commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +// @ts-ignore
Тоже не помогает. 
![image](https://user-images.githubusercontent.com/102280477/214088270-5fb3af18-d9a4-4b9f-bfe7-c54d2e791005.png)

2023-01-23 16:07 UTC, Gyxer513 commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +// @ts-ignore
Типизация ингредиента теперь правильная. 
![image](https://user-images.githubusercontent.com/102280477/214088979-e993474c-5d68-4997-9611-c8285a7700b9.png)

2023-01-23 16:08 UTC, Gyxer513 commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +// @ts-ignore
Типизация теперь правильная.

![image](https://user-images.githubusercontent.com/102280477/214089145-f7e90ee9-8a7c-46ef-8362-e89dd492465e.png)

2023-01-23 16:35 UTC, Gyxer513 commented
Спасибо за ревью. Все замечания исправлены.

2023-01-24 03:59 UTC, ArslanDev666 commented on src/services/store.ts
> +export type AppDispatch = typeof store.dispatch
Ну документация для этого и создана), чтобы правильно использовать инструмент)))

2023-01-24 04:32 UTC, ArslanDev666 commented on src/services/reducers/ingredients.ts
> +      reducer: (state, action: PayloadAction<Iingredient>) => {
**Надо исправить:**

тут должен был быть тип `IChoousenIngredients`, В прошлый раз что-то не заметил его, и подумал что там простой тип ингредиента))

2023-01-24 04:32 UTC, ArslanDev666 commented on src/services/types/store.ts
> +  chosenIngredients: IChoousenIngredients[] | [];
**Можно лучше:**

Здесь и в похожих местах.

Вам нет необходимости использовать дополнительно `|| []`, т.к. в тип массива уже входит пустой массив)

2023-01-24 04:32 UTC, ArslanDev666 commented on src/services/types/types.ts
> +  };
**Надо исправить:**

У вас неправильно описан тип дата, там должен быть тип ингредиента)

2023-01-24 04:32 UTC, ArslanDev666 commented on src/services/types/types.ts
> +  id: string;
**Можно лучше:**

Лучше не дублировать то, что уже есть в data)

2023-01-24 04:32 UTC, ArslanDev666 commented on src/components/BurgerConstructor/ConstructorItem.tsx
> +    // @ts-ignore
Ну он правильно ругается)) indexOf не стоит использовать таким образом, да и метод не самый подходящий)
Лучше использовать метод `findIndex`, и там по условию найти  нужный элемент. Укажу в комментарии к коду, как правильно

2023-01-24 04:46 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Проект теперь типизирован;

### **Осталось несколько небольших замечаний, которые нужно исправить, после этого работа будет принята:**

- Вам нет необходимости использовать дополнительно || [], т.к. в тип массива уже входит пустой массив)

  ```js
  // правильный вариант
  ingredients: Iingredient[];
  chosenIngredients: IChoousenIngredients[];
  ```

- и парочку замечаний отметил в коде.

### **Сделает код лучше:**

- Поработайте над неймингом типов/интерфейсов/пропсов, особенно обратите внимание на окончание слов (множ.число/ед.число)

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2023-01-24 04:46 UTC, ArslanDev666 commented on src/components/BurgerConstructor/ConstructorItem.tsx
> +    };
**Надо исправить:**

Ниже показан оптимальный вариант функции)
Убрал каррирование, не нужно оно там, мы можем сразу использовать нужные данные, т.к. имеем доступ к лексическому окружению внешней функции))
```js
const handleDeleteIngredient = () => {
      const updateIngredients = chosenIngredients.filter(
        ingredient => ingredient.randomId !== data.randomId
      );
      dispatch(deleteIngredient(updateIngredients));
};

// использование
handleClose={handleDeleteIngredient}
```
Это всё будет работать при условии что вы поправите тип 
```js
chosenIngredients: IChoousenIngredients[];
```

А также тип data в пропсах.

2023-01-24 04:46 UTC, ArslanDev666 commented on src/services/types/store.ts
> +  chosenIngredients: IChoousenIngredients[] | [];
**Надо исправить:**

Здесь и в похожих местах.

Вам нет необходимости использовать дополнительно `|| []`, т.к. в тип массива уже входит пустой массив)

2023-01-24 04:46 UTC, ArslanDev666 commented on src/services/reducers/ingredients.ts
> +        // @ts-ignore
**Надо исправить:**

тут должен был быть тип `IChoousenIngredients`, В прошлый раз что-то не заметил его, и подумал что там простой тип ингредиента))

2023-01-24 04:46 UTC, ArslanDev666 commented on src/services/types/types.ts
> +}
**Надо исправить:**

У вас неправильно описан тип дата, там должен быть тип ингредиента)

```js
data: IChoousenIngredients;
```

2023-01-24 04:46 UTC, ArslanDev666 commented on src/services/types/types.ts
> +  id: string;
Можно лучше:

Лучше не дублировать то, что уже есть в data)

2023-01-24 05:19 UTC, Gyxer513 commented on src/components/BurgerConstructor/ConstructorItem.tsx
> +    };
Исправлено, ошибки больше нет. Спасибо!

2023-01-24 05:20 UTC, Gyxer513 commented on src/services/types/store.ts
> +  chosenIngredients: IChoousenIngredients[] | [];
Исправлено.

2023-01-24 05:21 UTC, Gyxer513 commented on src/services/reducers/ingredients.ts
> +        // @ts-ignore
Помогло. Спасибо!

2023-01-24 05:21 UTC, Gyxer513 commented on src/services/types/types.ts
> +}
Исправил.

2023-01-24 05:23 UTC, Gyxer513 commented on src/services/types/types.ts
> +  id: string;
Исправлено.

2023-01-24 05:26 UTC, Gyxer513 commented
Здравствуйте! Все замечания исправлены, спасибо за ревью. 🌟🌟🌟

2023-01-24 05:37 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!🔥**

- Все замечания с прошлого ревью были исправлены.

### **Сделает код лучше:**

- Пусть главная страница всё таки будет находится по адресу '/' (сейчас она находится на роуте `/Stellar-Burgers`).

- Поработайте над неймингом типов/интерфейсов/пропсов, особенно обратите внимание на окончание слов (множ.число/ед.число)

2023-01-24 06:02 UTC, merged